version: '3.8'

services:
  database:
    container_name: postgres-golang-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      # - ./docker/postgres-data/:/var/lib/postgresql/data
      - golang-database:/var/lib/postgres
      - ./docker/postgres-data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: golang-database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5432
    networks:
      - golang-server-network

  mongo:
    image: mongo:latest
    container_name: mongo-golang-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: golang-database
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-data:/data/db

  redis:
    container_name: golang-redis
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - ./docker/redis-data:/data
    networks:
      - golang-server-network

networks:
  golang-server-network:
    driver: bridge

volumes:
  golang-database:
    driver: local
  mongo-database:
    driver: local
