version: '3.8'

services:
  database:
    container_name: postgres-golang-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - /docker/postgres-data/:/var/lib/postgresql/data
#      - ./docker/postgres:/docker-entrypoint-initdb.d
#      - golang-database:/var/lib/postgres
    environment:
      POSTGRES_DB: golang-database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5432
    networks:
      - golang-server-network

networks:
  golang-server-network:
    driver: bridge

volumes:
  golang-database:
    driver: local
