enable_swagger: true

app_info:
  environment: development
  api_port: :5000

database:
  host: localhost
  port: 5433
  username: root
  password: 123456
  database_name: golang-database

redis:
  host: localhost
  port: 6380
  prefix: golang-server
  username: root
  password: 123456
  db: 0

redis_queue:
  host: localhost
  port: 6380
  prefix: golang-server
  username: root
  password: 123456
  db: 1