apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgres-golang-database
        image: postgres:14.1
        env:
          - name: POSTGRES_DB
            value: "golang-database"
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "123456"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: postgresql-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
